### ISSUE TITLE
Itd be great if we could disable dragging

### ISSUE THREAD

**Issue by ElliotVilhelm** [rexxars/react-chess#2]
Then we could have a nice snap to grid effect

**Comment by ElliotVilhelm** [comment]
I achieved this by maintaining piece state and updating after validating move, if invalid move update to the incorrect state and again the the old state. Ugly work around.

**Comment by Sigmus** [comment]
Isn't ```allowMoves={false}``` what you need?

**Comment by ElliotVilhelm** [comment]
@Sigmus No, turning allowMoves off will not allow clicking moves either.
